# Site settings
title: Parker Ramsey, Software Developer
description: Professional Software Development Portfolio
baseurl: "parkerramsey.com" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Parker Ramsey
user_description: I am a Software Developer currently pursuing a Master of Entertainment Technology degree at Carnegie Mellon University's Entertainment Technology Center (ETC). This combination of engineering knowledge with interdisciplinary collaborative experience makes me especially qualified to work in the Entertainment Industry. I have a passion for entertainment and hope to work professionally in the Video Game Industry as a Software Developer.
user_title: Software Developer
email: parkerrmsy@gmail.com
twitter_username: CharliePRamsey
github_username:  CharliePRamsey
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
